# name: Update GitOps - event (prod)

# on:
#   workflow_run:
#     workflows:
#       - Build & Push Docker Image - event (prod) 
#     types:
#       - completed

# permissions:
#   contents: write  

# jobs:
#   update_gitops:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install kustomize
#         run: |
#           curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
#           sudo mv kustomize /usr/local/bin

#       - name: Checkout GitOps repo
#         uses: actions/checkout@v4
#         with:
#           repository: KTEventee/eventee-gitops
#           token: ${{ secrets.GITOPS_TOKEN }}
#           path: gitops

#       - name: Extract image tag from prod workflow
#         run: |
#           # workflow_run에서는 outputs을 직접 못 받으므로
#           # 커밋 SHA 기준으로 태그 재계산
#           SHORT_SHA="${{ github.event.workflow_run.head_sha }}"
#           TAG="prod-${SHORT_SHA:0:7}"

#           echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

#       - name: Set image URI
#         run: |
#           IMAGE_URI="637423360761.dkr.ecr.ap-northeast-2.amazonaws.com/eventee-event-service"
#           echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

#       - name: Update image in GitOps (kustomize)
#         run: |
#           cd gitops/prod/event
#           kustomize edit set image REPLACE_IMAGE_EVENT=${IMAGE_URI}:${IMAGE_TAG}

#       - name: Commit & push GitOps change
#         run: |
#           cd gitops
#           git config user.name "eventee-prod-ci"
#           git config user.email "ci@eventee.cloud"

#           git add -A
#           git diff --cached --quiet && echo "No changes to commit" && exit 0

#           git commit -m "(chore/prod): deploy event ${IMAGE_TAG}"
#           git push origin main
